title: "Notas"
description: "Notas convertidas desde Obsidian"
baseurl: "/notes" 
theme: minima
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      escape_liquid: true 
