title: "Notas"
description: "Notas convertidas desde Obsidian"
baseurl: "/notes" 
theme: minima
markdown: kramdown
permalink: pretty
render_liquid: false

defaults:
  - scope:
      path: ""
    values:
      escape_liquid: true
 
