name: Export Obsidian

on:
  push:
    branches: [ "master" ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and extract obsidian-export
        run: |
          # 1. Descarga el tar.xz
          curl -L https://github.com/zoni/obsidian-export/releases/download/v24.11.0/obsidian-export-x86_64-unknown-linux-gnu.tar.xz \
            -o obsidian-export.tar.xz

          # 2. Descomprime (crea la carpeta obsidian-export-x86_64-unknown-linux-gnu)
          tar xf obsidian-export.tar.xz

          # 3. Observa lo que se descomprimió
          ls -l
          ls -l obsidian-export-x86_64-unknown-linux-gnu

          # 4. Dar permisos de ejecución al binario (ajusta el nombre si difiere)
          chmod +x obsidian-export-x86_64-unknown-linux-gnu/obsidian-export
          file obsidian-export-x86_64-unknown-linux-gnu/obsidian-export

      - name: Run obsidian-export
        run: |
          mkdir -p export
          # Ejecutamos el binario dentro de la carpeta
          ./obsidian-export-x86_64-unknown-linux-gnu/obsidian-export vault/FEMPA export

      - name: Commit cleaned notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add export
        git commit -m "Automated export" || echo "No changes to commit"
        git push origin master

