name: Export Obsidian

on:
  push:
    branches: [ "master" ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download obsidian-export
        run: |
          curl -L \
            https://github.com/zoni/obsidian-export/releases/download/v0.6.0/obsidian-export_linux_amd64 \
            -o obsidian-export
          chmod +x obsidian-export
          file obsidian-export   # (opcional) para comprobar que es un binario Linux

      - name: Run obsidian-export
        run: |
          mkdir -p export
          ./obsidian-export vault export

      - name: Commit cleaned notes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add export
          git commit -m "Automated export" || echo "No changes to commit"
          git push
