name: Export Obsidian

on:
  push:
    branches: [ "master" ]  # tu rama

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download obsidian-export
        run: |
          curl -L https://github.com/zoni/obsidian-export/releases/download/v24.11.0/obsidian-export-x86_64-unknown-linux-gnu.tar.xz \
            -o obsidian-export.tar.xz
          tar xf obsidian-export.tar.xz
          ls -l

          chmod +x obsidian-export
          file obsidian-export
          head -n 5 obsidian-export

      - name: Run obsidian-export
        run: |
          mkdir -p export
          ./obsidian-export "vault/FEMPA" "export"

      - name: Commit cleaned notes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add export
          git commit -m "Automated export" || echo "No changes to commit"
          git push
