name: Export Obsidian

on:
  push:
    branches: [ "master" ]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # 1) Descarga el repositorio con tu vault
      - uses: actions/checkout@v3

      # 2) Instala Go (por ejemplo, versi칩n 1.20)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # 3) Instala obsidian-export desde GitHub con go install
      - name: Install obsidian-export
        run: go install github.com/zoni/obsidian-export@latest

      # 4) Ejecuta obsidian-export
      - name: Run obsidian-export
        run: |
          mkdir -p export
          # "obsidian-export" estar치 en tu GOPATH/bin. Normalmente en ~/go/bin/
          # A menudo basta con llamarlo directamente (Go lo a침ade al PATH en tiempo de ejecuci칩n)
          obsidian-export vault export

      # 5) Si quieres commitear la carpeta export/ al repo
      - name: Commit cleaned notes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add export
          git commit -m "Automated export" || echo "No changes to commit"
          git push
