name: Export Obsidian

on:
  push:
    branches: [ "main" ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and extract obsidian-export
        run: |
          curl -L https://github.com/zoni/obsidian-export/releases/download/v24.11.0/obsidian-export-x86_64-unknown-linux-gnu.tar.xz \
            -o obsidian-export.tar.xz

          tar xf obsidian-export.tar.xz

          ls -l
          ls -l obsidian-export-x86_64-unknown-linux-gnu

          chmod +x obsidian-export-x86_64-unknown-linux-gnu/obsidian-export
          file obsidian-export-x86_64-unknown-linux-gnu/obsidian-export

      - name: Run obsidian-export
        run: |
          ./obsidian-export-x86_64-unknown-linux-gnu/obsidian-export vault/FEMPA .

      - name: List files after export
        run: |
          ls -la
          
      - name: Commit cleaned notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add export
          git commit -m "Automated export" || echo "No changes to commit"
          git push
